import logging
import os
from pathlib import Path
from typing import Optional

from groq import Groq

from backend.config import GROQ_API_KEY

logger = logging.getLogger(__name__)

_GUARDRAILS_CONFIG_DIR = Path(__file__).parent / "guardrails"


class GuardrailsHandler:
    """
    Wraps LLM generation with optional NeMo input rails.

    Args:
        use_nemo: If True, load NeMo and run input rails. Output is always
                  generated by direct Groq call (Verification Agent handles
                  output safety). If False, skip NeMo entirely.
    """

    def __init__(
        self,
        config_dir: Path = _GUARDRAILS_CONFIG_DIR,
        use_nemo: bool = True,
    ) -> None:
        self._direct_client = Groq(api_key=GROQ_API_KEY)
        self._rails = None
        self._nemo_available = False

        if use_nemo:
            self._nemo_available = self._load_nemo(config_dir)

        status = "active (input rails only)" if self._nemo_available else "NOT active"
        logger.info("GuardrailsHandler: NeMo %s", status)

    def generate(
        self,
        system_prompt: str,
        user_message: str,
        model: str = "llama-3.3-70b-versatile",
        temperature: float = 0.0,
        max_tokens: int = 300,
    ) -> dict:
        """
        Generate a response. NeMo input rails run first; if they block the
        query, return the refusal message. Otherwise, call Groq directly.
        """
        # If NeMo is available, check input rails
        if self._nemo_available and self._rails is not None:
            nemo_result = self._check_input_rails(system_prompt, user_message)
            if nemo_result is not None:
                # Input rail blocked the query — return refusal
                return {
                    "content": nemo_result,
                    "nemo_active": True,
                    "nemo_intercepted": True,
                    "raw_content": nemo_result,
                    "model": model,
                }

        # Normal path: direct Groq call
        return self._generate_direct(
            system_prompt, user_message, model, temperature, max_tokens
        )

    def _load_nemo(self, config_dir: Path) -> bool:
        try:
            from nemoguardrails import LLMRails, RailsConfig  # noqa: PLC0415

            if not config_dir.exists():
                logger.warning("Guardrails config not found: %s", config_dir)
                return False

            os.environ["GROQ_API_KEY"] = GROQ_API_KEY or ""
            config = RailsConfig.from_path(str(config_dir))
            self._rails = LLMRails(config)
            logger.info("NeMo RailsConfig loaded from %s", config_dir)
            return True

        except ImportError:
            logger.warning("nemoguardrails not installed")
            return False
        except Exception as exc:
            logger.warning("Failed to load NeMo: %s", exc)
            return False

    def _check_input_rails(self, system_prompt: str, user_message: str) -> Optional[str]:
        """
        Run NeMo input rails. Returns a refusal message if the query is
        blocked, or None if the query is allowed through.

        NeMo 0.21.0: generate_async returns a dict. If content is non-empty,
        NeMo generated a response (blocked). If empty, query is clean.
        """
        import asyncio  # noqa: PLC0415

        try:
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message},
            ]

            result = asyncio.run(self._rails.generate_async(messages=messages))
            content = _extract_content(result)

            # If NeMo returned a non-empty response, it means an input rail
            # triggered and NeMo generated a refusal/bot message.
            if content.strip():
                logger.info(
                    "NeMo input rail triggered for: '%.60s...' | response: '%.60s...'",
                    user_message, content,
                )
                return content

            # Empty content = no input rail triggered, query is clean
            return None

        except Exception as exc:
            logger.exception("NeMo input rail check failed: %s", exc)
            # Fail open: if NeMo errors, allow the query through
            return None

    def _generate_direct(
        self,
        system_prompt: str,
        user_message: str,
        model: str,
        temperature: float,
        max_tokens: int,
    ) -> dict:
        """Direct Groq call — the single source of truth for generation."""
        response = self._direct_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message},
            ],
            temperature=temperature,
            max_tokens=max_tokens,
            stream=False,
        )
        content = response.choices[0].message.content or ""
        return {
            "content": content,
            "nemo_active": False,
            "nemo_intercepted": False,
            "raw_content": content,
            "model": model,
        }


def _extract_content(result) -> str:
    """
    Extract plain string content from NeMo 0.21.0's various return types.
    Handles: dict, list, str, and nested dicts.
    """
    if isinstance(result, str):
        return result

    if isinstance(result, dict):
        content = result.get("content", "")
        # Handle nested: {"role": "assistant", "content": {"role": "...", "content": "..."}}
        if isinstance(content, dict):
            content = content.get("content", "")
        return content if isinstance(content, str) else str(content)

    if isinstance(result, list) and result:
        last = result[-1]
        if isinstance(last, dict):
            content = last.get("content", "")
            if isinstance(content, dict):
                content = content.get("content", "")
            return content if isinstance(content, str) else str(content)
        return str(last)

    return str(result)